import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useApp } from '../../context/AppContext';
import { tenantList, readOverride, writeOverride, deepMerge } from '../../config';
import { cn, copyText, downloadFile } from '../../lib/utils';
import { summarize, clearEvents, getEvents } from '../../lib/analytics';
import { SECTION_TYPES } from '../registry';
import { Button, Icon, Badge, Tabs } from '../ui';

/**
 * Studio — the in-browser control room.
 *
 * This is what makes the template genuinely reusable: re-skin the site live,
 * reorder or disable sections, then export a config file for the next practice.
 * Open with ⌘/Ctrl + Shift + S, or `?studio=1`.
 */

const SWATCHES = [
  { name: 'Clinical teal', primary: '#0e8f6f', accent: '#0b7fc4', highlight: '#f0a325' },
  { name: 'Deep indigo', primary: '#4f46e5', accent: '#0ea5e9', highlight: '#f59e0b' },
  { name: 'Warm rose', primary: '#e11d64', accent: '#7c3aed', highlight: '#f59e0b' },
  { name: 'Forest', primary: '#15803d', accent: '#0d9488', highlight: '#ca8a04' },
  { name: 'Midnight blue', primary: '#1d4ed8', accent: '#0891b2', highlight: '#f97316' },
  { name: 'Plum', primary: '#7e22ce', accent: '#db2777', highlight: '#eab308' },
  { name: 'Terracotta', primary: '#c2410c', accent: '#0f766e', highlight: '#facc15' },
  { name: 'Slate pro', primary: '#334155', accent: '#0284c7', highlight: '#f59e0b' },
];

const FONTS = ['Outfit', 'Plus Jakarta Sans', 'Inter', 'Manrope', 'Sora', 'DM Sans', 'Figtree', 'Space Grotesk'];
const RADII = [
  { value: 'sharp', label: 'Sharp' },
  { value: 'soft', label: 'Soft' },
  { value: 'rounded', label: 'Rounded' },
  { value: 'pill', label: 'Pill' },
];

function Row({ label, hint, children }) {
  return (
    <div className="space-y-1.5">
      <span className="block text-[11px] font-extrabold uppercase tracking-wide text-ink-muted">{label}</span>
      {children}
      {hint && <span className="block text-[10px] text-ink-muted leading-relaxed">{hint}</span>}
    </div>
  );
}

const inputClass =
  'w-full bg-surface-2 border border-line rounded-md px-3 py-2 text-[13px] font-semibold text-ink focus:outline-none focus:border-brand-400 focus:ring-4 focus:ring-brand-500/10';

export default function Studio() {
  const { config, tenantId, switchTenant, applyOverride, appearance, setAppearance, toast } = useApp();
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState('brand');
  const [patch, setPatch] = useState(() => readOverride() || {});
  const patchRef = useRef(patch);
  patchRef.current = patch;

  // Enabled by ?studio=1, and always reachable via the keyboard shortcut.
  const [available, setAvailable] = useState(false);
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('studio') === '1') setAvailable(true);

    const onKey = (event) => {
      if ((event.metaKey || event.ctrlKey) && event.shiftKey && event.key.toLowerCase() === 's') {
        event.preventDefault();
        setAvailable(true);
        setOpen((v) => !v);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  const commit = (next) => {
    const merged = deepMerge(patchRef.current, { ...next, __tenant: tenantId });
    setPatch(merged);
    applyOverride(merged);
  };

  const reset = () => {
    setPatch({});
    writeOverride(null);
    applyOverride(null);
    toast('Studio changes discarded', { tone: 'default', icon: 'RefreshCw' });
  };

  const exportConfig = () => {
    const merged = deepMerge(config, {});
    delete merged.__tenantId;
    const body = `/**\n * Generated by Studio on ${new Date().toISOString().slice(0, 10)}.\n * Drop this into src/config/tenants/ and register it in src/config/index.js.\n */\n\nexport default ${JSON.stringify(
      merged,
      null,
      2,
    )};\n`;
    downloadFile(`${config.__tenantId || 'tenant'}.js`, body, 'text/javascript;charset=utf-8');
    toast('Config exported — drop it into src/config/tenants/', { tone: 'good', icon: 'Download' });
  };

  const copyPatch = async () => {
    const ok = await copyText(JSON.stringify(patch, null, 2));
    toast(ok ? 'Overrides copied as JSON' : 'Could not copy', { tone: ok ? 'good' : 'warn', icon: ok ? 'Check' : 'Info' });
  };

  const insights = useMemo(() => (open && tab === 'insights' ? summarize(getEvents()) : null), [open, tab]);

  if (!available) return null;

  const brand = config.brand;
  const sections = config.sections || [];

  const setSectionEnabled = (id, enabled) => {
    commit({ sections: sections.map((s) => (s.id === id ? { ...s, enabled } : s)) });
  };

  const moveSection = (index, delta) => {
    const next = [...sections];
    const target = index + delta;
    if (target < 0 || target >= next.length) return;
    [next[index], next[target]] = [next[target], next[index]];
    commit({ sections: next });
  };

  return createPortal(
    <>
      {/* launcher */}
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className={cn(
          'fixed z-[140] bottom-28 lg:bottom-6 left-6 w-12 h-12 rounded-full shadow-pop no-print',
          'bg-surface-inverse text-ink-inverse flex items-center justify-center cursor-pointer',
          'hover:scale-105 transition-transform',
        )}
        aria-label="Open Studio"
        title="Studio (⌘⇧S)"
      >
        <Icon name={open ? 'X' : 'Palette'} className="w-5 h-5" />
      </button>

      {/* panel */}
      <aside
        className={cn(
          'fixed z-[135] inset-y-0 left-0 w-full sm:w-[26rem] bg-surface border-r border-line shadow-pop no-print',
          'flex flex-col transition-transform duration-300',
          open ? 'translate-x-0' : '-translate-x-full',
        )}
        aria-hidden={!open}
      >
        <header className="px-5 py-4 border-b border-line flex items-start justify-between gap-3 flex-shrink-0">
          <div>
            <h2 className="font-heading font-extrabold text-lg text-ink flex items-center gap-2">
              <Icon name="Palette" className="w-4.5 h-4.5 text-brand-600 dark:text-brand-400" />
              Studio
            </h2>
            <p className="text-[11px] text-ink-muted mt-0.5">Re-skin this site live, then export the config.</p>
          </div>
          <button
            type="button"
            onClick={() => setOpen(false)}
            className="p-2 -mr-1 rounded-md text-ink-muted hover:text-ink hover:bg-surface-3 cursor-pointer"
            aria-label="Close Studio"
          >
            <Icon name="X" className="w-4 h-4" />
          </button>
        </header>

        <div className="px-5 py-3 border-b border-line flex-shrink-0">
          <Tabs
            tabs={[
              { value: 'brand', label: 'Brand', icon: 'Palette' },
              { value: 'sections', label: 'Sections', icon: 'ListChecks' },
              { value: 'content', label: 'Copy', icon: 'Pencil' },
              { value: 'insights', label: 'Insights', icon: 'Gauge' },
            ]}
            value={tab}
            onChange={setTab}
            size="sm"
          />
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-5 space-y-6">
          {/* ------------------------------------------------ brand */}
          {tab === 'brand' && (
            <>
              <Row label="Tenant" hint="Each tenant is one file in src/config/tenants/. Switching discards unsaved Studio edits.">
                <select value={tenantId} onChange={(event) => switchTenant(event.target.value)} className={inputClass}>
                  {tenantList().map((tenant) => (
                    <option key={tenant.id} value={tenant.id}>
                      {tenant.name} — {tenant.vertical}
                    </option>
                  ))}
                </select>
              </Row>

              <Row label="Palette presets">
                <div className="grid grid-cols-4 gap-2">
                  {SWATCHES.map((swatch) => {
                    const active = brand.colors.primary.toLowerCase() === swatch.primary.toLowerCase();
                    return (
                      <button
                        key={swatch.name}
                        type="button"
                        title={swatch.name}
                        onClick={() => commit({ brand: { colors: { ...swatch } } })}
                        className={cn(
                          'h-11 rounded-md border-2 overflow-hidden flex cursor-pointer transition-transform hover:scale-105',
                          active ? 'border-ink' : 'border-line',
                        )}
                      >
                        <span className="flex-1" style={{ background: swatch.primary }} />
                        <span className="w-1/4" style={{ background: swatch.accent }} />
                        <span className="w-1/4" style={{ background: swatch.highlight }} />
                      </button>
                    );
                  })}
                </div>
              </Row>

              <div className="grid grid-cols-3 gap-3">
                {['primary', 'accent', 'highlight'].map((key) => (
                  <Row key={key} label={key}>
                    <input
                      type="color"
                      value={brand.colors[key] || '#000000'}
                      onChange={(event) => commit({ brand: { colors: { [key]: event.target.value } } })}
                      className="w-full h-10 rounded-md border border-line bg-surface-2 cursor-pointer"
                    />
                  </Row>
                ))}
              </div>

              <Row label="Corner style">
                <div className="grid grid-cols-4 gap-2">
                  {RADII.map((radius) => (
                    <button
                      key={radius.value}
                      type="button"
                      onClick={() => commit({ brand: { radius: radius.value } })}
                      className={cn(
                        'py-2 text-[11px] font-bold border rounded-md cursor-pointer transition-colors',
                        brand.radius === radius.value
                          ? 'bg-brand-600 text-white border-brand-600'
                          : 'bg-surface-2 border-line text-ink-soft hover:border-brand-300',
                      )}
                    >
                      {radius.label}
                    </button>
                  ))}
                </div>
              </Row>

              <div className="grid grid-cols-2 gap-3">
                <Row label="Heading font">
                  <select
                    value={brand.fonts?.heading}
                    onChange={(event) => commit({ brand: { fonts: { heading: event.target.value } } })}
                    className={inputClass}
                  >
                    {FONTS.map((font) => (
                      <option key={font} value={font}>{font}</option>
                    ))}
                  </select>
                </Row>
                <Row label="Body font">
                  <select
                    value={brand.fonts?.body}
                    onChange={(event) => commit({ brand: { fonts: { body: event.target.value } } })}
                    className={inputClass}
                  >
                    {FONTS.map((font) => (
                      <option key={font} value={font}>{font}</option>
                    ))}
                  </select>
                </Row>
              </div>

              <Row label="Appearance">
                <div className="grid grid-cols-3 gap-2">
                  {['light', 'dark', 'system'].map((option) => (
                    <button
                      key={option}
                      type="button"
                      onClick={() => setAppearance(option)}
                      className={cn(
                        'py-2 text-[11px] font-bold border rounded-md cursor-pointer capitalize transition-colors',
                        appearance === option
                          ? 'bg-brand-600 text-white border-brand-600'
                          : 'bg-surface-2 border-line text-ink-soft hover:border-brand-300',
                      )}
                    >
                      {option}
                    </button>
                  ))}
                </div>
              </Row>
            </>
          )}

          {/* ------------------------------------------------ sections */}
          {tab === 'sections' && (
            <>
              <p className="text-[11px] text-ink-muted leading-relaxed">
                Toggle sections on and off, or reorder them. This is the whole page structure — it lives in
                <code className="mx-1 px-1 py-0.5 rounded bg-surface-3 text-[10px]">config.sections</code>.
              </p>

              <ul className="space-y-1.5">
                {sections.map((section, index) => (
                  <li
                    key={section.id}
                    className={cn(
                      'flex items-center gap-2 p-2.5 rounded-md border',
                      section.enabled === false ? 'bg-surface-2 border-line opacity-60' : 'bg-surface border-line',
                    )}
                  >
                    <button
                      type="button"
                      onClick={() => setSectionEnabled(section.id, section.enabled === false)}
                      className={cn(
                        'w-8 h-5 rounded-full relative transition-colors flex-shrink-0 cursor-pointer',
                        section.enabled === false ? 'bg-line' : 'bg-brand-600',
                      )}
                      aria-label={`Toggle ${section.id}`}
                      aria-pressed={section.enabled !== false}
                    >
                      <span
                        className={cn(
                          'absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform',
                          section.enabled === false ? 'left-0.5' : 'left-0.5 translate-x-3',
                        )}
                      />
                    </button>

                    <span className="flex-1 min-w-0">
                      <span className="block text-[12px] font-bold text-ink truncate">{section.nav || section.id}</span>
                      <span className="block text-[10px] text-ink-muted truncate">{section.component}</span>
                    </span>

                    <span className="flex flex-col gap-0.5 flex-shrink-0">
                      <button
                        type="button"
                        onClick={() => moveSection(index, -1)}
                        disabled={index === 0}
                        className="p-0.5 text-ink-muted hover:text-ink disabled:opacity-25 cursor-pointer disabled:cursor-not-allowed"
                        aria-label="Move up"
                      >
                        <Icon name="ChevronUp" className="w-3.5 h-3.5" />
                      </button>
                      <button
                        type="button"
                        onClick={() => moveSection(index, 1)}
                        disabled={index === sections.length - 1}
                        className="p-0.5 text-ink-muted hover:text-ink disabled:opacity-25 cursor-pointer disabled:cursor-not-allowed"
                        aria-label="Move down"
                      >
                        <Icon name="ChevronDown" className="w-3.5 h-3.5" />
                      </button>
                    </span>
                  </li>
                ))}
              </ul>

              <div className="rounded-md bg-surface-2 border border-line p-3.5 space-y-2">
                <p className="text-[10px] font-extrabold uppercase tracking-wide text-ink-muted">Available components</p>
                <div className="flex flex-wrap gap-1.5">
                  {SECTION_TYPES.map((type) => (
                    <Badge key={type} tone="neutral" size="xs">{type}</Badge>
                  ))}
                </div>
              </div>
            </>
          )}

          {/* ------------------------------------------------ copy */}
          {tab === 'content' && (
            <>
              <Row label="Business name">
                <input
                  value={brand.name}
                  onChange={(event) => commit({ brand: { name: event.target.value } })}
                  className={inputClass}
                />
              </Row>
              <Row label="Name accent">
                <input
                  value={brand.nameAccent || ''}
                  onChange={(event) => commit({ brand: { nameAccent: event.target.value } })}
                  className={inputClass}
                />
              </Row>
              <Row label="Tagline">
                <input
                  value={brand.tagline || ''}
                  onChange={(event) => commit({ brand: { tagline: event.target.value } })}
                  className={inputClass}
                />
              </Row>
              <Row label="Hero headline">
                <input
                  value={config.content.hero?.headline || ''}
                  onChange={(event) => commit({ content: { hero: { headline: event.target.value } } })}
                  className={inputClass}
                />
              </Row>
              <Row label="Hero accent words" hint="Rendered in the brand gradient.">
                <input
                  value={config.content.hero?.headlineAccent || ''}
                  onChange={(event) => commit({ content: { hero: { headlineAccent: event.target.value } } })}
                  className={inputClass}
                />
              </Row>
              <Row label="Hero sub-copy">
                <textarea
                  rows={4}
                  value={config.content.hero?.sub || ''}
                  onChange={(event) => commit({ content: { hero: { sub: event.target.value } } })}
                  className={cn(inputClass, 'resize-none leading-relaxed')}
                />
              </Row>
              <Row label="Primary CTA">
                <input
                  value={config.content.hero?.primaryCta || ''}
                  onChange={(event) => commit({ content: { hero: { primaryCta: event.target.value } } })}
                  className={inputClass}
                />
              </Row>
            </>
          )}

          {/* ------------------------------------------------ insights */}
          {tab === 'insights' && insights && (
            <>
              <p className="text-[11px] text-ink-muted leading-relaxed">
                Collected on this device only — no cookies, no third-party scripts. Point
                <code className="mx-1 px-1 py-0.5 rounded bg-surface-3 text-[10px]">integrations.analytics</code>
                at an endpoint to forward these.
              </p>

              <div className="grid grid-cols-3 gap-2">
                {[
                  { label: 'Events', value: insights.total },
                  { label: 'Sessions', value: insights.sessions },
                  { label: 'Book rate', value: `${insights.conversion}%` },
                ].map((stat) => (
                  <div key={stat.label} className="rounded-md bg-surface-2 border border-line p-3 text-center">
                    <span className="block font-heading font-extrabold text-xl text-ink tabular-nums">{stat.value}</span>
                    <span className="block text-[10px] font-bold uppercase tracking-wide text-ink-muted mt-0.5">
                      {stat.label}
                    </span>
                  </div>
                ))}
              </div>

              <div className="space-y-1.5">
                <p className="text-[10px] font-extrabold uppercase tracking-wide text-ink-muted">Most fired events</p>
                {insights.ranked.length === 0 && <p className="text-[12px] text-ink-muted">Nothing recorded yet.</p>}
                {insights.ranked.slice(0, 12).map(([name, count]) => (
                  <div key={name} className="flex items-center gap-2">
                    <span className="text-[11px] font-semibold text-ink-soft flex-1 truncate">{name}</span>
                    <span className="h-1.5 rounded-full bg-brand-500" style={{ width: `${Math.min(100, (count / insights.ranked[0][1]) * 90)}px` }} />
                    <span className="text-[11px] font-bold text-ink tabular-nums w-6 text-right">{count}</span>
                  </div>
                ))}
              </div>

              <Button
                onClick={() => {
                  clearEvents();
                  toast('Local analytics cleared', { tone: 'default', icon: 'RefreshCw' });
                  setTab('brand');
                }}
                variant="ghost"
                size="sm"
                icon="RefreshCw"
                full
              >
                Clear local data
              </Button>
            </>
          )}
        </div>

        <footer className="px-5 py-4 border-t border-line bg-surface-2 space-y-2 flex-shrink-0">
          <div className="grid grid-cols-2 gap-2">
            <Button onClick={exportConfig} size="sm" icon="Download">
              Export config
            </Button>
            <Button onClick={copyPatch} variant="outline" size="sm" icon="Copy">
              Copy changes
            </Button>
          </div>
          <Button onClick={reset} variant="ghost" size="sm" icon="RefreshCw" full>
            Discard Studio edits
          </Button>
        </footer>
      </aside>
    </>,
    document.body,
  );
}
